// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJmUqJc3m3ynkYl5vUtj52HGsAF_8SiDU',
    appId: '1:714431912734:web:389aa41a2444407eca070f',
    messagingSenderId: '714431912734',
    projectId: 'meal-6524a',
    authDomain: 'meal-6524a.firebaseapp.com',
    storageBucket: 'meal-6524a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbnLR0RlStyTDqu93jq4f0AfOHECN2lcE',
    appId: '1:714431912734:android:b6ab52670a98e1c7ca070f',
    messagingSenderId: '714431912734',
    projectId: 'meal-6524a',
    storageBucket: 'meal-6524a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCc-dqEpGim-5INmbI5wPlqzzch0jmQ-eA',
    appId: '1:714431912734:ios:993b610879080184ca070f',
    messagingSenderId: '714431912734',
    projectId: 'meal-6524a',
    storageBucket: 'meal-6524a.firebasestorage.app',
    iosBundleId: 'com.example.meal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCc-dqEpGim-5INmbI5wPlqzzch0jmQ-eA',
    appId: '1:714431912734:ios:993b610879080184ca070f',
    messagingSenderId: '714431912734',
    projectId: 'meal-6524a',
    storageBucket: 'meal-6524a.firebasestorage.app',
    iosBundleId: 'com.example.meal',
  );

}